export enum PermissionsItems {
    'USER_READ' = 'USER_READ',
    'USER_WRITE' = 'USER_WRITE',
    'SERVICE_READ' = 'SERVICE_READ',
    'SERVICE_WRITE' = 'SERVICE_READ',
    'CATEGORY_READ' = 'CATEGORY_READ',
    'CATEGORY_WRITE' = 'CATEGORY_WRITE',
    'EXPENSE_READ' = 'EXPENSE_READ',
    'EXPENSE_WRITE' = 'EXPENSE_WRITE'
  }